### ISSUE TITLE
Symfony console version is locked to 3.0

### ISSUE THREAD

**Issue by pthreat** [povils/figlet#6]
Tried to use your project but I'm using a newer console version, could you please bump it or just add ^3.0? 
Maybe just remove the command all together, I'm thinking most people having a use case for this lib will use symfony console anyway or any other console lib.

Great work on the lib, like it! 

Thanks

**Comment by pthreat** [comment]
Thanks @peter279k

**Comment by zaghadon** [comment]
#8 I had a similar issue, and I created a PR that should also fix it here.

**Comment by Meghabm07** [comment]
I'm having the same issue. I'm using the latest Symfony console (v6.2.1). Is it possible to change the Symfony console library version?

Thanks in advance.
